---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r4u
spec:
  selector:
    matchLabels:
      app: r4u
  replicas: 3
  template:
    metadata:
      labels:
        app: r4u
    spec:
      containers:
        - name: r4u
          image: r4u:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: r4udb
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
# This seperator --- below is MANDATORY!!!
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: r4u-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: r4u
  type: NodePort
